#!/usr/bin/env node
/**
 * Generates the crawlable half of the site from deals.json:
 *
 *   deal/<productId>.html   one static page per deal, own title/description/OG/JSON-LD
 *   theme/<theme>.html      one landing page per theme, linking every deal in it
 *   archive.html            plain-HTML index linking every deal page
 *   sitemap.xml             every URL above (plus the static pages at the root)
 *
 * The home page stays client-side and searchable; these pages exist so Google
 * has real HTML to index instead of an empty shell.
 *
 * Run:  node build.js                    (reads ./deals.json)
 *       node build.js --feed deals.sample.json --base https://brickdealil.com
 *
 * No dependencies, no framework. Commit the output.
 */

'use strict';

const fs = require('fs');
const { collapse } = require('./assets/collapse.js');
const { splitName } = require('./assets/name.js');
const path = require('path');

const args = process.argv.slice(2);
const argOf = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
};

const FEED = argOf('--feed', 'deals.json');
const BASE = argOf('--base', 'https://brickdealil.com').replace(/\/$/, '');
const OUT = argOf('--out', '.');

/* Theme landing pages target the long-tail searches ("הארי פוטר אליאקספרס",
   "טכניק תואם זול") and are the main internal-link path into the deal pages,
   which the home page can't provide - its cards must go to AliExpress.
   Related-deal blocks on each deal page do the same job one level down.

   Copy rule for everything generated here: the original brand's trademark
   never appears outside the footer disclaimer. "תואם" / "אבני בנייה תואמות"
   is the vocabulary. */
const RELATED_COUNT = 4;

/* Hand-written pages at the root that the sitemap must list. index.html is
   the home page; the rest are static copy. Not generated — just enumerated. */
const STATIC_PAGES = [
  { path: 'guide.html', freq: 'monthly', pri: '0.6' },
  { path: 'how-it-works.html', freq: 'monthly', pri: '0.5' },
  /* Extensionless on purpose — terms.html and privacy.html are served at /terms
     and /privacy (Caddy rewrites; see deploy/Caddyfile), and those are the URLs
     the TikTok app declares, so they are the ones the sitemap must list. */
  { path: 'terms', freq: 'yearly', pri: '0.2' },
  { path: 'privacy', freq: 'yearly', pri: '0.2' },
];

const TELEGRAM = 'https://t.me/+juxUyQ49on1mZGRk';

/* Brand assets ship in the repo, under assets/brand — the logo pack unpacked as
   delivered, so the next drop is a straight overwrite. Site-relative, because
   deal pages sit a directory down and reach them through `up`.

   OG_CARD is the exception: a scraper has no document base to resolve against,
   so og:image must be absolute. It is generated by tools/make-og-card.js — the
   pack has nothing at the 1.91:1 ratio link previews want. */
const BRAND = 'assets/brand';
const OG_CARD = `${BASE}/${BRAND}/og.png`;

/* Stands in for a deal whose feed record carries no image. Square and opaque,
   which is what the 600x600 slot on the deal page expects — the transparent
   lockups would show the page through their own letterforms. */
const DEAL_IMAGE_FALLBACK = `${BRAND}/png/brickdeal-instagram-avatar-dark.png`;

/* When the bot has verified a set number it swaps the seller photo for the
   official render (Brickset or BrickLink) and keeps the original under
   `sourceImage` — so `sourceImage` present means `image` is a render: an
   opaque white-background product shot that gets the white-tile treatment.

   Brickset also serves the same render at ~2150x2400 under /sets/large/. The
   grid keeps the small one; the deal page and its og:image get the large one.
   BrickLink has no documented larger variant, so those fall through as-is. */
const isRender = (d) => Boolean(d.sourceImage && d.image);

function largeRender(url) {
  const m = /^(https:\/\/images\.brickset\.com\/sets\/)images(\/[^/?#]+)$/.exec(String(url || ''));
  return m ? `${m[1]}large${m[2]}` : null;
}

const THEME_LABELS = {
  'harry-potter': 'הארי פוטר', 'star-wars': 'מלחמת הכוכבים', 'superheroes': 'גיבורי על',
  technic: 'טכניק', vehicles: 'רכבים', dinosaurs: 'דינוזאורים', flowers: 'פרחים וצמחים',
  fantasy: 'פנטזיה', space: 'חלל', pokemon: 'פוקימון', minecraft: 'מיינקראפט', anime: 'אנימה',
  city: 'עיר', friends: 'חברות', ninjago: 'נינג׳גו', disney: 'דיסני',
  architecture: 'ארכיטקטורה', trains: 'רכבות', boats: 'ספינות', castle: 'טירות ואבירים',
  military: 'צבאי', creator: 'קריאייטור', duplo: 'לפעוטות',
};

/** Escape for HTML text and double-quoted attributes. */
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

/** JSON-LD goes inside <script>; the only sequence that can break out is "</". */
const jsonld = (obj) => JSON.stringify(obj).replace(/</g, '\\u003c');

const money = (n) => (n % 1 === 0 ? String(n) : n.toFixed(2));

/** Product IDs become filenames — refuse anything that could escape the directory. */
const safeId = (id) => /^[A-Za-z0-9_-]{1,64}$/.test(String(id)) ? String(id) : null;

/* Set when the feed is the sample fixture. Every generated page then carries the
   same warning band as the index, so placeholder output can't be mistaken for
   the real site if it ever gets deployed by accident. */
let PLACEHOLDER_FEED = false;

const DEV_BANNER = '<div class="dev-banner">⚠ נתוני דוגמה — הקישורים אינם אמיתיים. אין להעלות גרסה זו לאוויר.</div>';

/** Site-relative prefix for a page: deal/ and theme/ sit a directory down. */
const upOf = (canonical) => (/\/(deal|theme)\//.test(canonical) ? '../' : '');

function shell({ title, description, canonical, ogImage, ogType = 'website', body, extraHead = '' }) {
  // One prefix, applied to every same-origin URL below, so the root and
  // subdirectory cases cannot drift apart.
  const up = upOf(canonical);

  return `<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${esc(canonical)}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta name="theme-color" content="#17181C">
<meta property="og:type" content="${esc(ogType)}">
<meta property="og:site_name" content="BrickDeal">
<meta property="og:locale" content="he_IL">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${esc(canonical)}">
<meta property="og:image" content="${esc(ogImage || OG_CARD)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(description)}">
<meta name="twitter:image" content="${esc(ogImage || OG_CARD)}">
<link rel="icon" href="${up}${BRAND}/favicon/favicon.ico" sizes="32x32">
<link rel="icon" href="${up}${BRAND}/favicon/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="${up}${BRAND}/favicon/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700;800;900&family=Space+Grotesk:wght@500;700&family=Yellowtail&display=swap">
<link rel="stylesheet" href="${up}assets/styles.css">
${extraHead}
</head>
<body>
${PLACEHOLDER_FEED ? DEV_BANNER : ''}
<header class="site-header">
  <div class="wrap site-header__inner">
    <a class="brand" href="${up || './'}">
      <img class="brand__logo" src="${up}${BRAND}/svg/brickdeal-lockup-he-on-dark.svg"
           alt="בריק דיל" width="733" height="202">
    </a>
    <nav class="site-nav" aria-label="ניווט ראשי">
      <a class="site-nav__link" href="https://www.instagram.com/brickdealil/" rel="noopener">אינסטגרם</a>
      <a class="site-nav__link" href="https://www.tiktok.com/@brickdealil" rel="noopener">טיקטוק</a>
      <a class="btn btn--tg" href="${TELEGRAM}" rel="noopener">ערוץ הטלגרם</a>
    </nav>
  </div>
</header>
<main><div class="wrap">
${body}
</div></main>
<aside class="cta">
  <div class="wrap cta__inner">
    <div>
      <p class="cta__title">דילים חדשים כל יום בטלגרם</p>
      <p class="cta__sub">אנחנו סורקים את אליאקספרס ושולחים רק את מה ששווה.</p>
    </div>
    <a class="btn btn--tg btn--lg" href="${TELEGRAM}" rel="noopener">הצטרפו לערוץ</a>
  </div>
</aside>
<footer class="site-footer">
  <div class="wrap">
    <p class="site-footer__links">
      <a href="${TELEGRAM}" rel="noopener">טלגרם</a>
      <a href="https://www.instagram.com/brickdealil/" rel="noopener">אינסטגרם</a>
      <a href="https://www.tiktok.com/@brickdealil" rel="noopener">טיקטוק</a>
      <a href="${up}archive.html">ארכיון הדילים</a>
      <a href="${up}guide.html">המדריך</a>
      <a href="${up}how-it-works.html">איך זה עובד</a>
      <!-- Root-absolute: /terms and /privacy are extensionless URLs (Caddy
           rewrites them to the .html files), so up has nothing to prefix. -->
      <a href="/terms">תקנון</a>
      <a href="/privacy">מדיניות פרטיות</a>
    </p>
    <p class="site-footer__disclosure">
      גילוי נאות: הקישורים באתר הם קישורי שותפים לאליאקספרס. אם תרכשו דרכם, נקבל עמלה מאליאקספרס.
      המחיר שאתם משלמים זהה — העמלה משולמת על ידי המוכר ולא על ידכם.
    </p>
    <p class="site-footer__disclosure">
      LEGO® הוא סימן מסחרי רשום של קבוצת LEGO, שאינה מקושרת לאתר זה ואינה מעורבת בו.
      המוצרים המוצגים הם אבני בנייה תואמות מיצרנים אחרים.
    </p>
    <div style="text-align: center; padding: 25px 0 0;">
      <blackz-signature></blackz-signature>
    </div>
  </div>
</footer>
<script src="${up}assets/blackz-signature.js" defer></script>
</body>
</html>
`;
}

const themeOf = (d) => (d.theme && THEME_LABELS[d.theme] ? d.theme : null);
const themeUrl = (key) => `${BASE}/theme/${key}.html`;

/** Static card, same markup and classes the client grid builds — but it links
 *  to the deal page, not to AliExpress. That is the point: these are the
 *  internal links that get deal pages crawled. `up` is the page's prefix. */
function cardHtml({ d, id }, up) {
  const { series, title } = splitName(d.name);
  const meta = [];
  if (d.pieces) meta.push(`<span class="card__meta-item"><bdi>${esc(new Intl.NumberFormat('en-US').format(d.pieces))} חלקים</bdi></span>`);
  if (d.setId) meta.push(`<span class="card__meta-item"><bdi>מק״ט ${esc(d.setId)}</bdi></span>`);
  if (d.stars) meta.push(`<span class="card__meta-item"><span class="card__star">★</span><bdi>${esc(Number(d.stars).toFixed(1))}</bdi></span>`);

  return `<a class="card" href="${up}deal/${esc(id)}.html">
    <div class="card__media${isRender(d) ? ' card__media--render' : ''}">
      <img class="card__img" src="${esc(d.image || `${up}${DEAL_IMAGE_FALLBACK}`)}" alt="${esc(d.name)}" width="400" height="400" loading="lazy" decoding="async">
    </div>
    <div class="card__body">
      <div class="card__price"><span class="card__amount">${esc(money(d.price))}</span><span class="card__currency">₪</span></div>
      ${series ? `<span class="card__series">${esc(series)}</span>` : ''}
      <h3 class="card__name">${esc(title)}</h3>
      ${meta.length ? `<p class="card__meta">${meta.join('')}</p>` : ''}
    </div>
  </a>`;
}

/** Scrolling chip row linking every theme page; `current` renders as "on". */
function themeChips(themes, up, current) {
  return `<nav class="chips chips--static" aria-label="לפי נושא">
${themes.map(({ key, label, rows }) => `  <a class="chip${key === current ? ' is-on' : ''}" href="${up}theme/${esc(key)}.html"${key === current ? ' aria-current="page"' : ''}>${esc(label)} <span class="chip__n">${rows.length}</span></a>`).join('\n')}
</nav>`;
}

function dealPage(d, id, { related, themes }) {
  const canonical = `${BASE}/deal/${id}.html`;
  // "<series> | <product>" — the series is shown as an eyebrow and the product
  // as the heading; d.name stays the full string wherever the deal is *named*.
  const { series, title } = splitName(d.name);
  const themeKey = themeOf(d);
  const themeName = (themeKey && THEME_LABELS[themeKey]) || series || null;

  // Trusted only when genuinely above the sale price — never derived.
  const was = Number(d.originalPrice) > Number(d.price) ? Number(d.originalPrice) : null;
  const discount = was ? Math.round((1 - d.price / was) * 100) : null;

  const specs = [];
  if (d.setId) specs.push(['מספר סט', d.setId]);
  if (d.pieces) specs.push(['מספר חלקים', new Intl.NumberFormat('en-US').format(d.pieces)]);
  if (d.stars) specs.push(['דירוג באליאקספרס', `${d.stars} מתוך 5`]);
  if (themeName) specs.push(['ערכת נושא', themeName]);
  if (d.priceCheckedAt) {
    specs.push(['המחיר נבדק', new Intl.DateTimeFormat('he-IL', {
      day: 'numeric', month: 'numeric', year: '2-digit',
    }).format(new Date(d.priceCheckedAt))]);
  }

  // Description leads with the facts a searcher scans for: price, pieces, set number.
  const descBits = [`${money(d.price)} ₪`];
  if (d.pieces) descBits.push(`${d.pieces} חלקים`);
  if (d.setId) descBits.push(`מק״ט ${d.setId}`);
  const description = `${d.name} — ${descBits.join(' · ')}. סט אבני בנייה תואם מאליאקספרס במחיר בשקלים, משלוח 2-4 שבועות. ${themeName ? 'נושא: ' + themeName + '. ' : ''}`.trim();

  const product = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: d.name,
    description,
    ...(themeName ? { category: themeName } : {}),
    offers: {
      '@type': 'Offer',
      price: Number(d.price).toFixed(2),
      priceCurrency: d.currency || 'ILS',
      availability: 'https://schema.org/InStock',
      itemCondition: 'https://schema.org/NewCondition',
      url: d.link,
    },
  };
  const large = isRender(d) ? largeRender(d.image) : null;
  if (d.image) product.image = large || d.image;
  if (d.setId) product.sku = d.setId;
  if (d.productId) product.productID = String(d.productId);
  if (d.stars) {
    product.aggregateRating = {
      '@type': 'AggregateRating', ratingValue: d.stars, bestRating: 5, ratingCount: 1,
    };
  }

  const crumbs = [{ '@type': 'ListItem', position: 1, name: 'דילים', item: `${BASE}/` }];
  if (themeKey) crumbs.push({ '@type': 'ListItem', position: 2, name: THEME_LABELS[themeKey], item: themeUrl(themeKey) });
  crumbs.push({ '@type': 'ListItem', position: crumbs.length + 1, name: d.name, item: canonical });
  const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: crumbs };

  // The series crumb links to the theme landing page when the theme is known.
  const seriesCrumb = series
    ? (themeKey
        ? `<a href="../theme/${esc(themeKey)}.html">${esc(series)}</a> › `
        : `${esc(series)} › `)
    : '';

  // Related deals: same theme first, newest overall otherwise. Either way the
  // page links onward to other deal pages, so none of them is a dead end.
  const relatedTitle = themeKey ? `עוד דילים בנושא ${THEME_LABELS[themeKey]}` : 'דילים נוספים';
  const relatedMore = themeKey
    ? `<a class="related__more" href="../theme/${esc(themeKey)}.html">לכל הדילים ב${esc(THEME_LABELS[themeKey])} ←</a>`
    : `<a class="related__more" href="../archive.html">לארכיון הדילים ←</a>`;
  const relatedHtml = related.length ? `
<section class="related" aria-labelledby="related-title">
  <div class="related__head">
    <h2 class="related__title" id="related-title">${esc(relatedTitle)}</h2>
    ${relatedMore}
  </div>
  <div class="grid">
${related.map((r) => cardHtml(r, '../')).join('\n')}
  </div>
</section>` : '';
  // The render's srcset widths are nominal — Brickset's actual pixel size varies
  // per set, but the small→large ratio (~3.5x) holds, which is all selection needs.
  const body = `<nav class="breadcrumb" aria-label="מיקום"><a href="../">דילים</a> › ${seriesCrumb}${esc(title)}</nav>

<article class="deal">
  <div class="deal__media${isRender(d) ? ' deal__media--render' : ''}">
    <img src="${esc(d.image || `../${DEAL_IMAGE_FALLBACK}`)}"${large ? ` srcset="${esc(d.image)} 618w, ${esc(large)} 2149w" sizes="(min-width: 760px) min(50vw, 560px), 100vw"` : ''} alt="${esc(d.name)}" width="600" height="600" loading="eager" decoding="async">
  </div>
  <div>
    ${series ? `<p class="deal__series">${esc(series)}</p>` : ''}
    <h1 class="deal__title">${esc(title)}</h1>
    <div class="deal__price"><span class="card__amount">${esc(money(d.price))}</span><span class="card__currency">₪</span></div>
    ${was ? `<p class="deal__was"><span class="fcard__was">${esc(money(was))} ₪</span> <span class="fcard__save">${discount}% הנחה</span></p>` : ''}
    <p class="page-sub">המחיר באליאקספרס, כולל משלוח לישראל.</p>

    ${specs.length ? `<ul class="deal__specs">
      ${specs.map(([k, v]) => `<li><span>${esc(k)}</span><strong>${esc(v)}</strong></li>`).join('\n      ')}
    </ul>` : ''}

    <p><a class="btn btn--tg btn--lg" href="${esc(d.link)}" target="_blank" rel="noopener sponsored">לצפייה באליאקספרס</a></p>
    <p class="page-sub">זהו סט אבני בנייה <strong>תואם</strong>, לא מוצר LEGO® מקורי. משלוח 2-4 שבועות מסין.
    המחיר משתנה — המחיר המחייב הוא זה שמופיע בדף המוצר. <a href="../guide.html">מזמינים בפעם הראשונה?</a></p>
  </div>
</article>
${relatedHtml}
${themes.length ? `\n<h2 class="related__themes-title">לפי נושא</h2>\n${themeChips(themes, '../', themeKey)}` : ''}`;

  // og:type product needs the price tags to go with it, per the OG spec.
  const productMeta = `<meta property="product:price:amount" content="${esc(Number(d.price).toFixed(2))}">
<meta property="product:price:currency" content="${esc(d.currency || 'ILS')}">`;

  return shell({
    title: `${d.name} – ${money(d.price)} ₪ | BrickDeal`,
    description,
    canonical,
    ogImage: large || d.image,
    ogType: 'product',
    body,
    extraHead: `${productMeta}\n<script type="application/ld+json">${jsonld(product)}</script>\n<script type="application/ld+json">${jsonld(breadcrumb)}</script>`,
  });
}

function themePage({ key, label, rows }, themes) {
  const canonical = themeUrl(key);
  const n = rows.length;

  const itemList = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: `${label} - סטים תואמים מאליאקספרס`,
    numberOfItems: n,
    itemListElement: rows.map(({ d, id }, i) => ({
      '@type': 'ListItem', position: i + 1, name: d.name, url: `${BASE}/deal/${id}.html`,
    })),
  };
  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'דילים', item: `${BASE}/` },
      { '@type': 'ListItem', position: 2, name: label, item: canonical },
    ],
  };

  const body = `<nav class="breadcrumb" aria-label="מיקום"><a href="../">דילים</a> › ${esc(label)}</nav>
<h1 class="page-title">${esc(label)} - אבני בנייה תואמות מאליאקספרס</h1>
<p class="page-sub">${n} סטים תואמים בנושא ${esc(label)} שמצאנו באליאקספרס, במחירים בשקלים.
לחיפוש וסינון לפי מחיר ומספר חלקים עברו <a href="../?theme=${esc(encodeURIComponent(key))}">לדף הראשי</a>.</p>
${themeChips(themes, '../', key)}
<div class="grid grid--static">
${rows.map((r) => cardHtml(r, '../')).join('\n')}
</div>
<p class="page-sub related__note">אלו סטים <strong>תואמים</strong> מיצרנים אחרים, לא מוצרי המותג המקורי. הכרטיס מוביל לדף הדיל, ומשם לאליאקספרס.
המחירים נבדקים כל לילה. המחיר המחייב הוא זה שבדף המוצר. <a href="../guide.html">מזמינים בפעם הראשונה?</a></p>`;

  return shell({
    title: `${label} - ${n} סטים תואמים מאליאקספרס במחיר זול | BrickDeal`,
    description: `כל הדילים על סטים של אבני בנייה תואמות בנושא ${label} מאליאקספרס: ${n} סטים במחירים בשקלים, עם מספר חלקים ודירוג. מתעדכן כל יום.`,
    canonical,
    body,
    extraHead: `<script type="application/ld+json">${jsonld(itemList)}</script>\n<script type="application/ld+json">${jsonld(breadcrumb)}</script>`,
  });
}

function archivePage(rows, themes) {
  const body = `<h1 class="page-title">ארכיון הדילים</h1>
<p class="page-sub">כל ${rows.length} הדילים על סטים תואמים מאליאקספרס שפורסמו, מהחדש לישן. לחיפוש וסינון עברו <a href="./">לדף הראשי</a>.</p>
${themes.length ? themeChips(themes, '', null) : ''}
<ul class="archive__list">
${rows.map(({ d, id }) => `  <li><a href="deal/${esc(id)}.html"><span>${esc(d.name)}</span><span class="archive__price">${esc(money(d.price))} ₪</span></a></li>`).join('\n')}
</ul>`;

  return shell({
    title: `ארכיון הדילים – ${rows.length} סטים של אבני בנייה תואמות | BrickDeal`,
    description: `רשימת כל ${rows.length} הדילים על סטים ואבני בנייה תואמות שפורסמו ב־BrickDeal.`,
    canonical: `${BASE}/archive.html`,
    body,
  });
}

function sitemap(rows, themes) {
  const urls = [
    { loc: `${BASE}/`, freq: 'daily', pri: '1.0' },
    { loc: `${BASE}/archive.html`, freq: 'daily', pri: '0.8' },
    ...STATIC_PAGES.map((p) => ({ loc: `${BASE}/${p.path}`, freq: p.freq, pri: p.pri })),
    ...themes.map(({ key }) => ({ loc: themeUrl(key), freq: 'daily', pri: '0.8' })),
    ...rows.map(({ d, id }) => ({
      loc: `${BASE}/deal/${id}.html`,
      freq: 'weekly',
      pri: '0.6',
      lastmod: d.priceCheckedAt ? String(d.priceCheckedAt).slice(0, 10) : null,
    })),
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${esc(u.loc)}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}
    <changefreq>${u.freq}</changefreq>
    <priority>${u.pri}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

function main() {
  if (!fs.existsSync(FEED)) {
    console.error(`build: ${FEED} not found.`);
    console.error('The bot export (Handoff #1 Part A) has to run first, or pass --feed deals.sample.json to preview.');
    process.exit(1);
  }

  const parsed = JSON.parse(fs.readFileSync(FEED, 'utf8'));
  const raw = Array.isArray(parsed) ? parsed : parsed.deals;
  if (!Array.isArray(raw)) {
    console.error(`build: ${FEED} must be an array or { deals: [...] }`);
    process.exit(1);
  }

  PLACEHOLDER_FEED = raw.some((d) => /placeholder|example\.invalid/i.test(String(d.link) + String(d.productId)));

  const skipped = [];
  const rows = [];

  for (const d of raw) {
    if (d.dead === true || d.available === false) { skipped.push(`${d.productId}: dead`); continue; }
    if (!d.name || !d.link || d.price == null) { skipped.push(`${d.productId}: missing name/link/price`); continue; }
    const id = safeId(d.productId);
    if (!id) { skipped.push(`${d.productId}: unusable id`); continue; }
    rows.push({ d, id });
  }

  /* Collapse duplicate listings of the same set, using the exact rule the
     client grid uses (assets/collapse.js). Runs AFTER the dead/invalid filter
     above so a dropped record can never win its group, and BEFORE sorting, so
     the page count, archive.html and sitemap.xml all describe the same set of
     deals the home page shows. */
  const keptRows = (() => {
    const byId = new Map(rows.map((r) => [String(r.d.productId), r]));
    const kept = collapse(rows.map((r) => r.d));
    return kept.map((d) => byId.get(String(d.productId))).filter(Boolean);
  })();
  if (keptRows.length !== rows.length) {
    console.log(`build: collapsed ${rows.length - keptRows.length} duplicate listing(s) -> ${keptRows.length} sets`);
  }
  rows.length = 0;
  rows.push(...keptRows);

  rows.sort((a, b) => new Date(b.d.postedAt || 0) - new Date(a.d.postedAt || 0));

  // One landing page per theme that actually has deals, in THEME_LABELS order
  // so the chip row reads the same on every page. Unknown keys get no page —
  // same rule as the client chips.
  const themes = Object.keys(THEME_LABELS)
    .map((key) => ({ key, label: THEME_LABELS[key], rows: rows.filter((r) => themeOf(r.d) === key) }))
    .filter((t) => t.rows.length);

  const dealDir = path.join(OUT, 'deal');
  const themeDir = path.join(OUT, 'theme');
  fs.mkdirSync(dealDir, { recursive: true });
  fs.mkdirSync(themeDir, { recursive: true });

  // Clear stale pages so a delisted deal or an emptied theme doesn't linger
  // as an orphan URL.
  for (const dir of [dealDir, themeDir]) {
    for (const f of fs.readdirSync(dir)) {
      if (f.endsWith('.html')) fs.unlinkSync(path.join(dir, f));
    }
  }

  for (const row of rows) {
    // Same theme first, then the newest deals overall to fill the row — a
    // theme with two deals shouldn't leave the page with one related card.
    const key = themeOf(row.d);
    const sameTheme = key ? themes.find((t) => t.key === key).rows : [];
    const related = [...sameTheme, ...rows]
      .filter((r, i, all) => r !== row && all.indexOf(r) === i)
      .slice(0, RELATED_COUNT);
    fs.writeFileSync(path.join(dealDir, `${row.id}.html`), dealPage(row.d, row.id, { related, themes }), 'utf8');
  }

  for (const t of themes) {
    fs.writeFileSync(path.join(themeDir, `${t.key}.html`), themePage(t, themes), 'utf8');
  }

  fs.writeFileSync(path.join(OUT, 'archive.html'), archivePage(rows, themes), 'utf8');
  fs.writeFileSync(path.join(OUT, 'sitemap.xml'), sitemap(rows, themes), 'utf8');

  console.log(`build: ${rows.length} deal pages + ${themes.length} theme pages + archive.html + sitemap.xml → ${path.resolve(OUT)}`);
  if (skipped.length) {
    console.log(`build: skipped ${skipped.length}:`);
    skipped.forEach((s) => console.log(`  - ${s}`));
  }
  if (PLACEHOLDER_FEED) {
    console.warn('\nbuild: ⚠ feed contains PLACEHOLDER links — this output must not be deployed.');
    console.warn('build:   every generated page carries a visible warning band.');
  }
}

main();
